# Generated by Django 3.0 on 2020-01-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informations_generales',
            fields=[
                ('representants_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='representants_id')),
                ('adresse', models.CharField(max_length=30, verbose_name='adresse')),
                ('code_postal', models.CharField(max_length=30, verbose_name='code_postal')),
                ('derniere_publication_activite', models.CharField(max_length=30, verbose_name='derniere_publication_activite')),
                ('date_premiere_publication', models.CharField(max_length=30, verbose_name='date_premiere_publication')),
                ('declaration_organisation_appartenance', models.CharField(max_length=30, verbose_name='declaration_organisation_appartenance')),
                ('declaration_tiers', models.CharField(max_length=30, verbose_name='declaration_tiers')),
                ('denomination', models.CharField(max_length=30, verbose_name='denomination')),
                ('identifiant_national', models.CharField(max_length=30, verbose_name='identifiant_national')),
                ('activites_publiees', models.CharField(max_length=30, verbose_name='activites_publiees')),
                ('page_facebook', models.CharField(max_length=30, verbose_name='page_facebook')),
                ('page_linkedin', models.CharField(max_length=30, verbose_name='page_linkedin')),
                ('page_twitter', models.CharField(max_length=30, verbose_name='page_twitter')),
                ('site_web', models.CharField(max_length=30, verbose_name='site_web')),
                ('nom_usage_HATVP', models.CharField(max_length=30, verbose_name='nom_usage_HATVP')),
                ('pays', models.CharField(max_length=30, verbose_name='pays')),
                ('sigle_HATVP', models.CharField(max_length=30, verbose_name='sigle_HATVP')),
                ('type_identifiant_national', models.CharField(max_length=30, verbose_name='type_identifiant_national')),
                ('ville', models.CharField(max_length=30, verbose_name='ville')),
                ('label_categorie_organisation', models.CharField(max_length=30, verbose_name='label_categorie_organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Dirigeants',
            fields=[
                ('civilite_dirigeant', models.CharField(max_length=30, verbose_name='civilite_dirigeant')),
                ('fonction_dirigeant', models.CharField(max_length=30, verbose_name='fonction_dirigeant')),
                ('nom_dirigeant', models.CharField(max_length=30, verbose_name='nom_dirigeant')),
                ('prenom_dirigeant', models.CharField(max_length=30, verbose_name='prenom_dirigeant')),
                ('representants_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pythonApp.Informations_generales')),
                ('nom_prenom_dirigeant', models.CharField(max_length=30, verbose_name='nom_prenom_dirigeant')),
            ],
        ),
    ]
