# Generated by Django 3.0.1 on 2020-01-31 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercices',
            fields=[
                ('exercices_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='exercices_id')),
                ('date_debut', models.CharField(max_length=30, verbose_name='date_debut')),
                ('date_fin', models.CharField(max_length=30, verbose_name='date_fin')),
                ('exercice_sans_activite', models.CharField(max_length=30, verbose_name='exercice_sans_activite')),
                ('nombre_activites', models.IntegerField(verbose_name='nombre_activites')),
                ('declaration_incomplete', models.CharField(max_length=3, verbose_name='declaration_incomplete')),
                ('date_publication', models.CharField(max_length=30, verbose_name='date_publication')),
                ('exercice_sans_CA', models.CharField(max_length=30, verbose_name='exercice_sans_CA')),
                ('montant_depense', models.CharField(max_length=30, verbose_name='montant_depense')),
                ('nombre_salaries', models.CharField(max_length=30, verbose_name='nombre_salaries')),
                ('chiffre_affaires', models.CharField(max_length=30, verbose_name='chiffre_affaires')),
                ('annee_debut', models.CharField(max_length=30, verbose_name='annee_debut')),
                ('annee_fin', models.CharField(max_length=30, verbose_name='annee_fin')),
                ('montant_depense_inf', models.CharField(max_length=30, verbose_name='montant_depense_inf')),
                ('montant_depense_sup', models.CharField(max_length=30, verbose_name='montant_depense_sup')),
                ('ca_inf', models.FloatField(max_length=30, verbose_name='ca_inf')),
                ('ca_sup', models.CharField(max_length=30, verbose_name='ca_sup')),
            ],
        ),
        migrations.CreateModel(
            name='Informations_generales',
            fields=[
                ('representants_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='representants_id')),
                ('adresse', models.CharField(max_length=30, verbose_name='adresse')),
                ('code_postal', models.CharField(max_length=30, verbose_name='code_postal')),
                ('derniere_publication_activite', models.CharField(max_length=30, verbose_name='derniere_publication_activite')),
                ('date_premiere_publication', models.CharField(max_length=30, verbose_name='date_premiere_publication')),
                ('declaration_organisation_appartenance', models.CharField(max_length=30, verbose_name='declaration_organisation_appartenance')),
                ('declaration_tiers', models.CharField(max_length=30, verbose_name='declaration_tiers')),
                ('denomination', models.CharField(max_length=30, verbose_name='denomination')),
                ('identifiant_national', models.CharField(max_length=30, verbose_name='identifiant_national')),
                ('activites_publiees', models.CharField(max_length=30, verbose_name='activites_publiees')),
                ('page_facebook', models.CharField(max_length=30, verbose_name='page_facebook')),
                ('page_linkedin', models.CharField(max_length=30, verbose_name='page_linkedin')),
                ('page_twitter', models.CharField(max_length=30, verbose_name='page_twitter')),
                ('site_web', models.CharField(max_length=30, verbose_name='site_web')),
                ('nom_usage_HATVP', models.CharField(max_length=30, verbose_name='nom_usage_HATVP')),
                ('pays', models.CharField(max_length=30, verbose_name='pays')),
                ('sigle_HATVP', models.CharField(max_length=30, verbose_name='sigle_HATVP')),
                ('type_identifiant_national', models.CharField(max_length=30, verbose_name='type_identifiant_national')),
                ('ville', models.CharField(max_length=30, verbose_name='ville')),
                ('label_categorie_organisation', models.CharField(max_length=30, verbose_name='label_categorie_organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Objets_activites',
            fields=[
                ('activite_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='activite_id')),
                ('date_publication_activite', models.CharField(blank=True, max_length=30, null=True)),
                ('identifiant_fiche', models.CharField(blank=True, max_length=30, null=True)),
                ('objet_activite', models.CharField(blank=True, max_length=30, null=True)),
                ('exercice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Exercices')),
            ],
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('action_representation_interet_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='activite_id')),
                ('observation', models.CharField(max_length=30, verbose_name='domaineIntervention')),
                ('activite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Objets_activites')),
            ],
        ),
        migrations.CreateModel(
            name='Ministeres_aai_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_public', models.CharField(max_length=30, verbose_name='responsable_public')),
                ('departement_ministeriel', models.CharField(max_length=30, verbose_name='departement_ministeriel')),
                ('responsable_public_ou_dpt_ministeriel_autre', models.CharField(max_length=30, verbose_name='responsable_public_ou_dpt_ministeriel_autre')),
                ('action_representation_interet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Observations')),
            ],
        ),
        migrations.AddField(
            model_name='exercices',
            name='representants_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Informations_generales'),
        ),
        migrations.CreateModel(
            name='Domaines_intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaineIntervention', models.CharField(max_length=30, verbose_name='domaineIntervention')),
                ('activite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Objets_activites')),
            ],
        ),
        migrations.CreateModel(
            name='Decisions_concernees',
            fields=[
                ('decision_concerne', models.IntegerField(primary_key=True, serialize=False, verbose_name='activite_id')),
                ('action_representation_interet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Observations')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire_action_menee', models.CharField(max_length=30, verbose_name='beneficiaire_action_menee')),
                ('action_menee_en_propre', models.CharField(max_length=30, verbose_name='action_menee_en_propre')),
                ('action_representation_interet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Observations')),
            ],
        ),
        migrations.CreateModel(
            name='Actions_menees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_menee', models.CharField(max_length=30, verbose_name='action_menee')),
                ('action_menee_autre', models.CharField(max_length=30, verbose_name='action_menee_autre')),
                ('action_representation_interet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Observations')),
            ],
        ),
    ]
