# Generated by Django 3.0.1 on 2020-01-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('representants_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='representants_id')),
                ('date_premiere_publication', models.DateTimeField(verbose_name='date_premiere_publication')),
                ('declaration_organisation_appartenance', models.BooleanField(verbose_name='declaration_organisation_appartenance')),
                ('declaration_tiers', models.BooleanField(verbose_name='declaration_tiers')),
                ('denomination', models.CharField(max_length=30, verbose_name='denomination')),
                ('identifiant_national', models.IntegerField(verbose_name='identifiant_national')),
                ('activites_publiees', models.BooleanField(verbose_name='activites_publiees')),
                ('type_identifiant_national', models.CharField(max_length=30, verbose_name='type_identifiant_national')),
                ('exercices_id', models.IntegerField(verbose_name='exercices_id')),
                ('date_debut', models.DateField(verbose_name='date_debut')),
                ('date_fin', models.DateField(verbose_name='date_fin')),
                ('exercice_sans_activite', models.BooleanField(verbose_name='exercice_sans_activite')),
                ('nombre_activites', models.IntegerField(verbose_name='nombre_activites')),
                ('declaration_incomplete', models.BooleanField(verbose_name='declaration_incomplete')),
                ('date_publication', models.DateField(verbose_name='date_publication')),
                ('exercice_sans_CA', models.CharField(max_length=30, verbose_name='exercice_sans_CA')),
                ('montant_depense', models.CharField(max_length=30, verbose_name='montant_depense')),
                ('nombre_salaries', models.FloatField(verbose_name='nombre_salaries')),
                ('chiffre_affaires', models.CharField(max_length=30, verbose_name='chiffre_affaires')),
                ('annee_debut', models.IntegerField(verbose_name='annee_debut')),
                ('annee_fin', models.IntegerField(verbose_name='annee_fin')),
                ('montant_depense_inf', models.IntegerField(verbose_name='montant_depense_inf')),
                ('montant_depense_sup', models.IntegerField(verbose_name='montant_depense_sup')),
                ('ca_inf', models.IntegerField(verbose_name='ca_inf')),
                ('ca_sup', models.FloatField(verbose_name='ca_sup')),
                ('activite_id', models.FloatField(verbose_name='activite_id')),
                ('date_publication_activite', models.DateField(verbose_name='date_publication_activite')),
                ('identifiant_fiche', models.CharField(max_length=30, verbose_name='identifiant_fiche')),
                ('objet_activite', models.CharField(max_length=30, verbose_name='objet_activite')),
                ('domaines_intervention_actions_menees', models.CharField(max_length=30, verbose_name='domaines_intervention_actions_menees')),
                ('action_representation_interet_id', models.FloatField(verbose_name='action_representation_interet_id')),
                ('responsable_public', models.CharField(max_length=30, verbose_name='responsable_public')),
                ('departement_ministeriel', models.CharField(max_length=30, verbose_name='departement_ministeriel')),
                ('beneficiaire_action_menee', models.CharField(max_length=30, verbose_name='beneficiaire_action_menee')),
                ('action_menee', models.CharField(max_length=30, verbose_name='action_menee')),
                ('decision_concernee', models.CharField(max_length=30, verbose_name='decision_concernee')),
            ],
        ),
    ]
