# Generated by Django 3.0.1 on 2020-01-31 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dirigeants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite_dirigeant', models.CharField(blank=True, max_length=13, null=True)),
                ('fonction_dirigeant', models.CharField(blank=True, max_length=119, null=True)),
                ('nom_dirigeant', models.CharField(blank=True, max_length=39, null=True)),
                ('prenom_dirigeant', models.CharField(blank=True, max_length=31, null=True)),
                ('nom_prenom_dirigeant', models.CharField(blank=True, max_length=45, null=True)),
                ('representants_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Informations_generales')),
            ],
        ),
    ]
