# Generated by Django 3.0.1 on 2020-01-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='action_representation_interet_id',
            field=models.CharField(max_length=30, verbose_name='action_representation_interet_id'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='activite_id',
            field=models.CharField(max_length=30, verbose_name='activite_id'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='annee_debut',
            field=models.CharField(max_length=30, verbose_name='annee_debut'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='annee_fin',
            field=models.CharField(max_length=30, verbose_name='annee_fin'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ca_inf',
            field=models.CharField(max_length=30, verbose_name='ca_inf'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ca_sup',
            field=models.CharField(max_length=30, verbose_name='ca_sup'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='date_debut',
            field=models.CharField(max_length=30, verbose_name='date_debut'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='date_fin',
            field=models.CharField(max_length=30, verbose_name='date_fin'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='date_premiere_publication',
            field=models.CharField(max_length=30, verbose_name='date_premiere_publication'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='date_publication',
            field=models.CharField(max_length=30, verbose_name='date_publication'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='date_publication_activite',
            field=models.CharField(max_length=30, verbose_name='date_publication_activite'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='declaration_incomplete',
            field=models.CharField(max_length=30, verbose_name='declaration_incomplete'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='declaration_organisation_appartenance',
            field=models.BooleanField(max_length=30, verbose_name='declaration_organisation_appartenance'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='declaration_tiers',
            field=models.BooleanField(max_length=30, verbose_name='declaration_tiers'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='exercice_sans_activite',
            field=models.CharField(max_length=30, verbose_name='exercice_sans_activite'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='exercices_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='organization',
            name='identifiant_national',
            field=models.CharField(max_length=30, verbose_name='identifiant_national'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='montant_depense_inf',
            field=models.CharField(max_length=30, verbose_name='montant_depense_inf'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='montant_depense_sup',
            field=models.CharField(max_length=30, verbose_name='montant_depense_sup'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='nombre_activites',
            field=models.CharField(max_length=30, verbose_name='nombre_activites'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='nombre_salaries',
            field=models.CharField(max_length=30, verbose_name='nombre_salaries'),
        ),
    ]
