# Generated by Django 3.0.1 on 2020-01-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApp', '0002_actions_menees_affiliations_beneficiaires_clients_collaborateurs_decisions_concernees_dirigeants_dom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercices',
            name='montant_depense_inf',
            field=models.IntegerField(verbose_name='montant_depense_inf'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='montant_depense_sup',
            field=models.IntegerField(verbose_name='montant_depense_sup'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='nombre_activites',
            field=models.IntegerField(verbose_name='nombre_activites'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='nombre_salaries',
            field=models.IntegerField(verbose_name='nombre_salaries'),
        ),
    ]
