# Generated by Django 3.0.1 on 2020-01-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApp', '0002_auto_20200131_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decisions_concernees',
            old_name='decision_concerne',
            new_name='Decisions_concernees',
        ),
        migrations.DeleteModel(
            name='Domaines_intervention',
        ),
    ]
