# Generated by Django 3.0.1 on 2020-01-31 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApp', '0003_auto_20200131_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur_activites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur_activite', models.CharField(max_length=30, verbose_name='secteur_activite')),
                ('representants_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Informations_generales')),
            ],
        ),
        migrations.CreateModel(
            name='Niveaux_intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_intervention', models.CharField(max_length=30, verbose_name='niveau_intervention')),
                ('representants_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Informations_generales')),
            ],
        ),
        migrations.CreateModel(
            name='Domaines_intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaineIntervention', models.CharField(max_length=30, verbose_name='domaineIntervention')),
                ('activite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Objets_activites')),
            ],
        ),
        migrations.CreateModel(
            name='Dirigeants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite_dirigeant', models.CharField(blank=True, max_length=13, null=True)),
                ('fonction_dirigeant', models.CharField(blank=True, max_length=119, null=True)),
                ('nom_dirigeant', models.CharField(blank=True, max_length=39, null=True)),
                ('prenom_dirigeant', models.CharField(blank=True, max_length=31, null=True)),
                ('nom_prenom_dirigeant', models.CharField(blank=True, max_length=45, null=True)),
                ('representants_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Informations_generales')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborateurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite_collaborateur', models.CharField(max_length=30, verbose_name='civilite_collaborateur')),
                ('fonction_collaborateur', models.CharField(max_length=30, verbose_name='fonction_collaborateur')),
                ('nom_collaborateur', models.CharField(max_length=30, verbose_name='nom_collaborateur')),
                ('prenom_collaborateur', models.CharField(max_length=30, verbose_name='prenom_collaborateur')),
                ('nom_prenom_collaborateur', models.CharField(max_length=30, verbose_name='nom_prenom_collaborateur')),
                ('representants_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Informations_generales')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination_client', models.CharField(max_length=30, verbose_name='denomination_client')),
                ('identifiant_national_client', models.CharField(max_length=30, verbose_name='identifiant_national_client')),
                ('type_identifiant_national_client', models.CharField(max_length=30, verbose_name='type_identifiant_national_client')),
                ('representants_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Informations_generales')),
            ],
        ),
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination_affiliation', models.CharField(max_length=30, verbose_name='denomination_affiliation')),
                ('identifiant_national_client', models.CharField(max_length=30, verbose_name='identifiant_national_client')),
                ('type_identifiant_national_client', models.CharField(max_length=30, verbose_name='type_identifiant_national_client')),
                ('representants_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.Informations_generales')),
            ],
        ),
    ]
