# Generated by Django 3.0 on 2020-01-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApp', '0004_auto_20200131_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaires',
            name='action_representation_interet_id',
        ),
        migrations.RemoveField(
            model_name='decisions_concernees',
            name='action_representation_interet_id',
        ),
        migrations.RemoveField(
            model_name='domaines_intervention',
            name='activite_id',
        ),
        migrations.RemoveField(
            model_name='exercices',
            name='representants_id',
        ),
        migrations.RemoveField(
            model_name='ministeres_aai_api',
            name='action_representation_interet_id',
        ),
        migrations.RemoveField(
            model_name='objets_activites',
            name='exercice_id',
        ),
        migrations.RemoveField(
            model_name='observations',
            name='activite_id',
        ),
        migrations.DeleteModel(
            name='Actions_menees',
        ),
        migrations.DeleteModel(
            name='Beneficiaires',
        ),
        migrations.DeleteModel(
            name='Decisions_concernees',
        ),
        migrations.DeleteModel(
            name='Domaines_intervention',
        ),
        migrations.DeleteModel(
            name='Exercices',
        ),
        migrations.DeleteModel(
            name='Ministeres_aai_api',
        ),
        migrations.DeleteModel(
            name='Objets_activites',
        ),
        migrations.DeleteModel(
            name='Observations',
        ),
    ]
