# Generated by Django 3.0 on 2020-01-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApp', '0005_auto_20200131_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations_generales',
            name='representants_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='representants_id'),
        ),
    ]
